<?php

/**
 * @file
 * Contains mt_countdown.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mt_countdown_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mt_countdown module.
    case 'help.page.mt_countdown':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Configure the content and layout of the Count Down.') . '</p>';

      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mt_countdown_theme() {
  // Theme for mt_countdown block.
  $themes['mt_countdown'] = [
    'template'  => 'mt_countdown',
    'variables' => [
      'data' => NULL,
    ],
  ];

  $themes['html__mt_countdown'] = [
    'base hook' => 'html',
    'template'  => 'html--mt_countdown',
    'variables' => [
      'data' => NULL,
    ],
  ];

  return $themes;

}

/**
 * Implements hook_page_attachments().
 */
function mt_countdown_page_attachments(array &$attachments) {

  $config = \Drupal::config('mt_countdown.settings');

  // Set data to drupal settings.
  $attachments['#attached']['drupalSettings']['mt_countdown']['expiration_date'] = $config->get('expiration_date');

  // Attach library.
  $attachments['#attached']['library'][] = 'mt_countdown/mt_countdown';
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function mt_countdown_theme_suggestions_html(array $variables) {
  $template_suggestions = array();
  $template_suggestions[] = 'html__mt_countdown';

  return $template_suggestions;
}

/**
 * Implements hook_preprocess().
 */
function mt_countdown_preprocess_html(&$variables) {

  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  if ($is_admin) {
    $variables['admin_part'] = TRUE;
  } else {
    $variables['admin_part'] = FALSE;
  }

  $config = \Drupal::config('mt_countdown.settings');
  $variables['title'] = $config->get('title');
  $variables['alert_message'] = $config->get('alert_message');
  $variables['days_to'] = $config->get('days_to');
  $variables['target_url'] = $config->get('target_url');
  $variables['dismiss_text'] = $config->get('dismiss_text');

  $predefined_palettes = $config->get('predefined_palettes');
  $variables['predefined_palettes'] = $predefined_palettes ? '' : 'mt-count-down-theme';

  $variables['background'] = $config->get('background');
  $variables['title_color'] = $config->get('title_color');
  $variables['message_color'] = $config->get('message_color');
  $variables['notes_color'] = $config->get('notes_color');
  $variables['button_background'] = $config->get('button_background');
  $variables['button_color'] = $config->get('button_color');

}
